# Generated by Django 6.0 on 2026-01-16 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(blank=True, max_length=100, null=True)),
                ('job', models.CharField(blank=True, max_length=100, null=True)),
                ('sal', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('dept_no', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('grade', models.SmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('low_sal', models.IntegerField(blank=True, null=True)),
                ('high_sal', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('emp_no', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=100)),
                ('job', models.CharField(blank=True, max_length=100, null=True)),
                ('hiredate', models.DateField(blank=True, null=True)),
                ('sal', models.IntegerField(blank=True, null=True)),
                ('comm', models.IntegerField(blank=True, null=True)),
                ('dept_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dept')),
                ('mgr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.emp')),
            ],
        ),
    ]
