# Generated by Django 6.0 on 2026-01-08 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dept',
            old_name='dept_id',
            new_name='dept_no',
        ),
        migrations.RenameField(
            model_name='emp',
            old_name='dept_id',
            new_name='dept_no',
        ),
        migrations.RenameField(
            model_name='emp',
            old_name='emp_id',
            new_name='emp_no',
        ),
        migrations.RemoveField(
            model_name='bonus',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='bonus',
            name='emp_id',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='emp_id',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='id',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='salary',
        ),
        migrations.AddField(
            model_name='bonus',
            name='ename',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bonus',
            name='job',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bonus',
            name='sal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dept',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='emp',
            name='comm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emp',
            name='hiredate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emp',
            name='job',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='emp',
            name='mgr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.emp'),
        ),
        migrations.AddField(
            model_name='emp',
            name='sal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salary',
            name='grade',
            field=models.SmallIntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='salary',
            name='high_sal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salary',
            name='low_sal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
