# Generated by Django 6.0 on 2026-01-07 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.SmallIntegerField(primary_key=True, serialize=False, unique=True)),
                ('country_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('capital_id', models.SmallIntegerField(primary_key=True, serialize=False, unique=True)),
                ('capital_name', models.CharField(max_length=100, unique=True)),
                ('country_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.country')),
            ],
        ),
    ]
